// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnaHbvtEohBqyxB8pA4Uqe7xLDs6fKH2w',
    appId: '1:573829770831:web:663d30e3ca0fd0ee51843a',
    messagingSenderId: '573829770831',
    projectId: 'wise-46f92',
    authDomain: 'wise-46f92.firebaseapp.com',
    storageBucket: 'wise-46f92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsf-2fOKE202oKX1q0p7hqPPbALHPy1Lg',
    appId: '1:573829770831:android:e7d3d7e22f9bb23b51843a',
    messagingSenderId: '573829770831',
    projectId: 'wise-46f92',
    storageBucket: 'wise-46f92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVJw0kYvb3jc2pyYnZJ7uArA4rnBR8roo',
    appId: '1:573829770831:ios:62c029ed1813634b51843a',
    messagingSenderId: '573829770831',
    projectId: 'wise-46f92',
    storageBucket: 'wise-46f92.firebasestorage.app',
    iosBundleId: 'com.example.wiseplug',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnaHbvtEohBqyxB8pA4Uqe7xLDs6fKH2w',
    appId: '1:573829770831:web:82c4b4632d8785a351843a',
    messagingSenderId: '573829770831',
    projectId: 'wise-46f92',
    authDomain: 'wise-46f92.firebaseapp.com',
    storageBucket: 'wise-46f92.firebasestorage.app',
  );
}
